package litesrc

import (
	"strings"
	"testing"
)

func TestKinovodParseQualityList(t *testing.T) {
	in := "[1080p]https://cdn.example/1080.m3u8,[720p]https://cdn.example/720.m3u8,[480p]https://cdn.example/480.m3u8"
	got := kinovodParseQualityList(in)
	if len(got) != 3 {
		t.Fatalf("expected 3 qualities, got %d", len(got))
	}
	if got[0].Label != "1080p" || !strings.HasSuffix(got[0].URL, "/1080.m3u8") {
		t.Errorf("top quality wrong: %+v", got[0])
	}
	// 4K should rank higher than 1080.
	in2 := "[720p]https://x/720.m3u8,[4K]https://x/4k.m3u8,[1080p]https://x/1080.m3u8"
	got2 := kinovodParseQualityList(in2)
	if got2[0].Label != "4K" {
		t.Errorf("expected 4K first, got %q", got2[0].Label)
	}
}

func TestKinovodParseSubtitleList(t *testing.T) {
	in := "[ru]https://s/ru.vtt,[en]https://s/en.vtt"
	got := kinovodParseSubtitleList(in)
	if len(got) != 2 {
		t.Fatalf("expected 2 subtitles, got %d", len(got))
	}
	if got[0].Label != "ru" || got[0].URL != "https://s/ru.vtt" {
		t.Errorf("first subtitle wrong: %+v", got[0])
	}
}

func TestKinovodParseTranslationList(t *testing.T) {
	in := "{Дубляж}https://s/dub.m3u8;{Оригинал}https://s/orig.m3u8"
	got := kinovodParseTranslationList(in)
	if len(got) != 2 {
		t.Fatalf("expected 2 voices, got %d", len(got))
	}
	if got[0].Voice != "Дубляж" || got[0].URL != "https://s/dub.m3u8" {
		t.Errorf("first voice wrong: %+v", got[0])
	}
	// Voice with embedded quality list should resolve to top quality URL.
	in2 := "{Pro}[1080p]https://x/1080.m3u8,[720p]https://x/720.m3u8;{LostFilm}https://x/lf.m3u8"
	got2 := kinovodParseTranslationList(in2)
	if got2[0].URL != "https://x/1080.m3u8" {
		t.Errorf("voice with quality list: expected 1080p URL, got %q", got2[0].URL)
	}
}

func TestKinovodParseMovie(t *testing.T) {
	payload := "file|[1080p]https://cdn/1080.m3u8,[720p]https://cdn/720.m3u8|[ru]https://s/ru.vtt"
	streams, subs := kinovodParseMovie(payload)
	if len(streams) != 2 {
		t.Fatalf("expected 2 streams, got %d", len(streams))
	}
	if streams[0].Label != "1080p" {
		t.Errorf("top stream wrong: %+v", streams[0])
	}
	if len(subs) != 1 || subs[0].Label != "ru" {
		t.Errorf("subs wrong: %+v", subs)
	}
}

func TestKinovodParseSerial(t *testing.T) {
	// Python repr-style payload. Kinovod's pars_seria walks this exact shape.
	payload := "pl|" +
		`[{'comment':'1 сезон','folder':[` +
		`{'comment':'1 серия','file':'[1080p]https:\/\/cdn\/s01e01_1080.m3u8,[720p]https:\/\/cdn\/s01e01_720.m3u8','subtitle':None},` +
		`{'comment':'2 серия','file':'[1080p]https:\/\/cdn\/s01e02_1080.m3u8','subtitle':None}` +
		`]}]` +
		"|"
	serial := kinovodParseSerial(payload)
	if len(serial) != 1 {
		t.Fatalf("expected 1 season, got %d", len(serial))
	}
	s := serial[0]
	if len(s.Episodes) != 2 {
		t.Fatalf("expected 2 episodes, got %d", len(s.Episodes))
	}
	if s.Episodes[0].SingleURL != "https://cdn/s01e01_1080.m3u8" {
		t.Errorf("episode 1 URL wrong: %q", s.Episodes[0].SingleURL)
	}
}

func TestKinovodParseSerialVoiceFile(t *testing.T) {
	payload := "pl|" +
		`[{'comment':'1 сезон','folder':[` +
		`{'comment':'1 серия','file':'{Pro}https:\/\/cdn\/pro_s01e01.m3u8;{LostFilm}https:\/\/cdn\/lf_s01e01.m3u8','subtitle':None}` +
		`]}]` +
		"|"
	serial := kinovodParseSerial(payload)
	if len(serial) != 1 || len(serial[0].Episodes) != 1 {
		t.Fatalf("unexpected serial shape")
	}
	ep := serial[0].Episodes[0]
	if len(ep.Voices) != 2 {
		t.Fatalf("expected 2 voices on first episode, got %d", len(ep.Voices))
	}
	if ep.Voices[0].Voice != "Pro" || ep.Voices[0].URL != "https://cdn/pro_s01e01.m3u8" {
		t.Errorf("first voice wrong: %+v", ep.Voices[0])
	}
}

func TestKinovodPyLitToJSON(t *testing.T) {
	in := `[{'a':1,'b':None,'c':True,'d':'string with \"quote\"','e':False}]`
	out := kinovodPyLitToJSON(in)
	if !strings.Contains(out, `"a"`) || !strings.Contains(out, `"b":null`) {
		t.Errorf("py→json conversion missing fields: %s", out)
	}
	if !strings.Contains(out, `"c":true`) || !strings.Contains(out, `"e":false`) {
		t.Errorf("py→json bool conversion broken: %s", out)
	}
}

func TestKinovodHunterDecode(t *testing.T) {
	// Fixture generated by /tmp/hunter_gen.py — see commit message. Encoded
	// plaintext: 'var _vod_hash = "abc123XYZ"; var _vod_time = "1700000000";'
	// using alphabet="qweRtyUiopAsdfGh", base=10, offset=12.
	encoded := "wRqAwqpAweUAttAwqiAwRqAweRAwweAwqiAwwUAwqpAweiAwwUAttAiRAttAtUAwqpAwwqAwwwAUwAUeAURAwqqAwqwAwqeAtUAiwAttAwRqAwqpAweUAttAwqiAwRqAweRAwweAwqiAweoAwwiAwewAwwRAttAiRAttAtUAUwAUiAUqAUqAUqAUqAUqAUqAUqAUqAtUAiwA"
	// Wrap in the signature the regex looks for. The middle integer (u) and
	// trailing integer (r) are not used by the decoder; values are arbitrary.
	wrapped := `<script>escape(r))}("` + encoded + `",1,"qweRtyUiopAsdfGh",12,10,1))</script>`
	got, err := kinovodHunterDecode(wrapped)
	if err != nil {
		t.Fatalf("hunter decode err: %v", err)
	}
	want := `var _vod_hash = "abc123XYZ"; var _vod_time = "1700000000";`
	if got != want {
		t.Fatalf("hunter decode mismatch\n  got:  %q\n  want: %q", got, want)
	}

	// Make sure the post-decode regexes pull out the right values.
	hash := submatch1(kinovodVodInnerHash, got)
	vTime := submatch1(kinovodVodInnerTime, got)
	if hash != "abc123XYZ" {
		t.Errorf("vod_hash extraction wrong: %q", hash)
	}
	if vTime != "1700000000" {
		t.Errorf("vod_time extraction wrong: %q", vTime)
	}
}

func TestKinovodParseMovieMetaPage(t *testing.T) {
	pageHTML := `
		<html><body>
		<script>
		var MOVIE_ID = 12345;
		var IDENTIFIER = "abcdef0123456789";
		var PLAYER_CUID = "cuid_xxx";
		var VOD_HASH = "deadbeef";
		var VOD_TIME = "1700000000";
		</script>
		</body></html>`
	c := &kinovodChecker{}
	meta := c.parseMovieMeta(pageHTML)
	if meta.MovieID != "12345" || meta.Identifier != "abcdef0123456789" {
		t.Errorf("movie/identifier wrong: %+v", meta)
	}
	if meta.VodHash != "deadbeef" || meta.VodTime != "1700000000" {
		t.Errorf("vod_hash/time wrong: %+v", meta)
	}
	if meta.CUID != "cuid_xxx" {
		t.Errorf("cuid wrong: %+v", meta)
	}
}
