package cluster

import (
	"bytes"
	"io"
	"net/http"
	"strings"
	"time"

	"lampac-go/internal/httpclient"

	"github.com/rs/zerolog/log"
)

// Forwarder proxies HTTP requests to cluster nodes with retry-on-5xx support.
type Forwarder struct {
	pool        *Pool
	liteClient  *http.Client // short timeout for /lite/*
	proxyClient *http.Client // long timeout for /proxy/*
}

// NewForwarder creates a forwarder backed by the given pool.
func NewForwarder(pool *Pool) *Forwarder {
	return &Forwarder{
		pool: pool,
		// Редиректы нод отдаём клиенту как есть. Клиент по умолчанию шёл по 302
		// сам: нода отвечала 302 на /proxy/<токен> — пересыл шагал туда через
		// публичный хост и тянул ВСЁ видео через main (manifest.mp4 у zetflix:
		// 206 на main с p50 5.5 с и до 62 с, разбор 22.09.2026); с torrent_direct
		// так же утёк бы поток бэкенда. Плеер по 302 ходит сам.
		liteClient:  httpclient.NewNoRedirect(30 * time.Second),
		proxyClient: httpclient.NewNoRedirect(5 * time.Minute),
	}
}

// Forward proxies the request, retrying on a different node if the first
// attempt returns a 5xx or fails entirely.
//
// Returns true if any node ultimately served a response back to the client
// (regardless of upstream status). Returns false only if no node could be
// reached at all and the caller should fall back to local handling.
func (f *Forwarder) Forward(w http.ResponseWriter, r *http.Request, primary *Node) bool {
	maxRetries := f.pool.CurrentSettings().MaxRetries
	tried := map[string]bool{primary.ID: true}

	// For non-idempotent requests with a body we'd need to buffer to enable
	// retries. /lite/* and /proxy/* in this codebase are effectively GET
	// (chi router only registers GET for these paths), so we proxy the body
	// as-is on the first attempt. If we need to retry, we use a fresh empty
	// body — safe because all retried endpoints are GET.
	var bodyBuf []byte
	if r.Body != nil && r.ContentLength > 0 && r.ContentLength < 1<<20 {
		b, _ := io.ReadAll(r.Body)
		_ = r.Body.Close()
		bodyBuf = b
		r.Body = io.NopCloser(bytes.NewReader(b))
	}

	target := primary
	for attempt := 0; attempt <= maxRetries; attempt++ {
		ok, retriable := f.tryOnce(w, r, target, attempt == 0, bodyBuf)
		if ok {
			return true
		}
		if !retriable {
			return false // response was already partially written — can't retry
		}
		// Try next-best candidate, skipping ones already attempted.
		candidates := f.pool.PickRetryCandidates(maxRetries-attempt, tried)
		if len(candidates) == 0 {
			return false
		}
		target = candidates[0]
		tried[target.ID] = true
		log.Debug().Str("retry-to", target.Host).Int("attempt", attempt+1).Msg("cluster: retry forward")
	}
	return false
}

// tryOnce performs a single forward attempt.
// Returns (responseFullyWritten, isRetriable).
//   - (true, _)       — response served to client, we're done.
//   - (false, true)   — no headers written yet, safe to retry on another node.
//   - (false, false)  — partial response written; caller cannot retry.
func (f *Forwarder) tryOnce(w http.ResponseWriter, r *http.Request, node *Node, firstAttempt bool, bodyBuf []byte) (bool, bool) {
	f.pool.IncrConns(node)
	defer f.pool.DecrConns(node)

	target := node.Host + r.URL.Path
	if r.URL.RawQuery != "" {
		target += "?" + r.URL.RawQuery
	}

	client := f.liteClient
	if strings.HasPrefix(r.URL.Path, "/proxy/") || strings.HasPrefix(r.URL.Path, "/proxy-dash/") {
		client = f.proxyClient
	}

	var bodyReader io.Reader
	if firstAttempt {
		bodyReader = r.Body
	} else if bodyBuf != nil {
		bodyReader = bytes.NewReader(bodyBuf)
	}

	req, err := http.NewRequestWithContext(r.Context(), r.Method, target, bodyReader)
	if err != nil {
		log.Debug().Err(err).Str("node", node.Host).Msg("cluster: forward request creation failed")
		f.pool.MarkFailedRequest(node, 0, err.Error())
		return false, true
	}

	copyHeaders(r.Header, req.Header)
	req.Header.Set("X-Cluster-Key", f.pool.APIKey())

	clientIP := extractClientIP(r)
	if clientIP != "" {
		if existing := req.Header.Get("X-Forwarded-For"); existing != "" {
			req.Header.Set("X-Forwarded-For", existing+", "+clientIP)
		} else {
			req.Header.Set("X-Forwarded-For", clientIP)
		}
		req.Header.Set("X-Real-IP", clientIP)
	}

	// Propagate the ORIGINAL public-facing host + scheme to the node so any
	// absolute URLs generated by balancers on the node (e.g. `/proxy/<hash>`
	// wrappers in stream_proxy.go) point back at the primary, not the node.
	// Without this, hostFromRequest(req) on the node returns the node's own
	// internal host like "193.233.231.225:888" and clients receive broken
	// stream URLs (e.g. HTTPS scheme against an HTTP-only node port).
	if origHost := strings.TrimSpace(r.Host); origHost != "" {
		req.Header.Set("X-Forwarded-Host", origHost)
	}
	if origScheme := requestScheme(r); origScheme != "" {
		req.Header.Set("X-Forwarded-Proto", origScheme)
	}

	start := time.Now()
	resp, err := client.Do(req)
	if err != nil {
		latency := time.Since(start).Milliseconds()
		log.Debug().Err(err).Str("node", node.Host).Str("path", r.URL.Path).Msg("cluster: forward request failed")
		f.pool.MarkFailedRequest(node, latency, err.Error())
		return false, true
	}
	defer resp.Body.Close()

	// Retry on 5xx — but only if we haven't started writing the response yet.
	if resp.StatusCode >= 500 && resp.StatusCode < 600 {
		latency := time.Since(start).Milliseconds()
		f.pool.MarkFailedRequest(node, latency, "HTTP "+resp.Status)
		return false, true
	}

	// Copy the upstream node's response headers, then attach this node's
	// X-Lampac-Server identifier.
	applyUpstreamHeaders(w.Header(), resp.Header)
	w.Header().Set("X-Lampac-Server", node.Name)
	w.Header().Set("X-Lampac-Server-Host", trimScheme(node.Host))
	w.WriteHeader(resp.StatusCode)

	var bytesStreamed int64
	if flusher, ok := w.(http.Flusher); ok {
		buf := make([]byte, 32*1024)
		for {
			n, readErr := resp.Body.Read(buf)
			if n > 0 {
				if _, writeErr := w.Write(buf[:n]); writeErr != nil {
					// Client gone — count as served (response was on the wire).
					lat := time.Since(start).Milliseconds()
					bal := extractBalancer(r.URL.Path)
					f.pool.MarkSuccessRequest(node, lat)
					node.RecordRequest(bal, clientIP, bytesStreamed)
					f.pool.RecordForwardEvent(node, bal, clientIP, resp.StatusCode, bytesStreamed, lat, false)
					return true, false
				}
				bytesStreamed += int64(n)
				flusher.Flush()
			}
			if readErr != nil {
				break
			}
		}
	} else {
		n, _ := io.Copy(w, resp.Body)
		bytesStreamed = n
	}

	lat := time.Since(start).Milliseconds()
	bal := extractBalancer(r.URL.Path)
	f.pool.MarkSuccessRequest(node, lat)
	node.RecordRequest(bal, clientIP, bytesStreamed)
	f.pool.RecordForwardEvent(node, bal, clientIP, resp.StatusCode, bytesStreamed, lat, false)
	return true, false
}

// extractBalancer parses the balancer name from a /lite/{name}/... or
// /proxy/... path. Returns "" if the path doesn't match a known shape.
func extractBalancer(path string) string {
	if strings.HasPrefix(path, "/lite/") {
		rest := path[len("/lite/"):]
		if i := strings.IndexByte(rest, '/'); i > 0 {
			return rest[:i]
		}
		if i := strings.IndexAny(rest, "?#"); i > 0 {
			return rest[:i]
		}
		return rest
	}
	if strings.HasPrefix(path, "/proxy/") {
		return "proxy"
	}
	return ""
}

func copyHeaders(src, dst http.Header) {
	skip := map[string]bool{
		"Connection":          true,
		"Keep-Alive":          true,
		"Transfer-Encoding":   true,
		"Te":                  true,
		"Trailer":             true,
		"Upgrade":             true,
		"Proxy-Authorization": true,
		"Proxy-Connection":    true,
	}
	for k, vals := range src {
		if skip[k] {
			continue
		}
		for _, v := range vals {
			dst.Add(k, v)
		}
	}
}

// applyUpstreamHeaders copies a forwarded node's response headers onto dst.
//
// By the time the forward handler runs, the local middleware chain
// (globalCORSMiddleware, requestIDMiddleware) has already written CORS +
// X-Request-Id onto dst. The upstream node runs the same middleware and returns
// its own copies, so a plain Add would emit BOTH sets and the client ends up
// with two Access-Control-Allow-Origin / X-Request-Id headers. Browsers reject
// any response carrying more than one Access-Control-Allow-Origin value, which
// silently breaks cross-origin plugin fetches (the canonical case: a Lampa
// front-end on lampa.mx calling a forwarded route on this host).
//
// Del-then-Add per key makes the upstream response authoritative without
// duplicating: a header the upstream sets replaces whatever the middleware put
// there, a header it doesn't set is left untouched, and a header that is
// legitimately repeated (e.g. multiple Set-Cookie, which arrive as several
// values under one key) keeps all of its values.
func applyUpstreamHeaders(dst, src http.Header) {
	for k, vals := range src {
		dst.Del(k)
		for _, v := range vals {
			dst.Add(k, v)
		}
	}
}

func extractClientIP(r *http.Request) string {
	if xff := strings.TrimSpace(r.Header.Get("X-Forwarded-For")); xff != "" {
		parts := strings.Split(xff, ",")
		if ip := strings.TrimSpace(parts[0]); ip != "" {
			return ip
		}
	}
	if xr := strings.TrimSpace(r.Header.Get("X-Real-IP")); xr != "" {
		return xr
	}
	if idx := strings.LastIndex(r.RemoteAddr, ":"); idx > 0 {
		return r.RemoteAddr[:idx]
	}
	return r.RemoteAddr
}

func trimScheme(host string) string {
	h := strings.TrimPrefix(host, "https://")
	return strings.TrimPrefix(h, "http://")
}

// requestScheme returns "https" if the request looks like it came in over TLS
// (direct or via a TLS-terminating proxy), else "http". Mirrors hostFromRequest
// in httpapi/plugins.go without importing it.
func requestScheme(r *http.Request) string {
	if xf := strings.TrimSpace(r.Header.Get("X-Forwarded-Proto")); xf != "" {
		return xf
	}
	if r.TLS != nil {
		return "https"
	}
	return "http"
}
